FORMAT: 1A
 
# classification-api

Classification api defines interface for taxonomy module

## species [/species]

### Get species [GET]

>#### Request: /species 
 + Context
    + locale
 + Query parameters
    + UUID
    + canonicalName 
     
 + Response 200 (application/json) 
 
        {
            "meta" : {
                "resultLanguages" : locale,
                "apiVersion" : "0",
                "callDate" : "Jun 12, 2016 at 16.37.49",    
                "resultCount" : 2,
                "contentLicenses" : null,
                "callEndpoint" : "https://server/classifications/version/species?name={canonicalName}&uuid={uuid}", 
                "statusCode" : 200,
                "maintenanceContact" : "admin@dina-system.org",
                "supportedLanguages" : [
                    "GB_en",
                    "SE_sv"
                ]
            },
            "data" : [
                {
                    "id" : 4,
                    "type" : "taxon",
                    "attributes" : {  
                        "id" : "4"
                    } 
                },
                {
                    "id" : 5,
                    "type" : "taxon", 
                    "attributes" : { 
                        "id" : "5", 
                    }
                }  
            ] 
        }
        
## Species /{id} [/collections/v0/{entity}/{id}]

### Get entity by id [GET]
Retrieves single record from database by the *entity name* and *id*

> #### Request: /collections/v0/{entity}/{id}
 + Path parameters:
    + entity - String [Name of the entity]
    + id     - int or String [The entity id]
     
 + Response 200 (application/json) 
 
        {
            "meta" : {
                "callEndpoint" : "https://beta-api.dina-web.net/collections/v0/Agent/8",
                "contentLicenses" : null,
                "callDate" : "Jun 12, 2016 at 15.38.54",
                "statusCode" : 200,
                "apiVersion" : "0",
                "sortOrder" : null, 
                "maintenanceContact" : "admin@dina-system.org", 
                "message" : null,
                "resultLanguages" : null,
                "resultCount" : 1,
                "previous" : null,
                "next" : null,
                "orderBy" : null,
                "supportedLanguages" : [
                    "GB_en",
                    "SE_sv"
                ]
            },
            "data" : {
                "type" : "Agent",
                "id" : 8,
                "attributes" : {
                    "dateOfBirth" : null,
                    "timestampModified" : 1463731167000,
                    "remarks" : null,
                    "createdByAgentID" : "1",
                    "suffix" : null,
                    "dateOfDeath" : null,
                    "firstName" : "Johan",
                    "dateOfDeathPrecision" : 1,
                    "url" : null,
                    "email" : null,
                    "abbreviation" : "",
                    "id" : "8",
                    "timestampCreated" : 1463731167000,
                    "initials" : null,
                    "agentType" : 1,
                    "dateOfBirthPrecision" : 1,
                    "guid" : null,
                    "middleInitial" : null,
                    "agentID" : 8,
                    "lastName" : "Johnsson",
                    "interests" : null,
                    "divisionID" : "2",
                    "modifiedByAgentID" : "1",
                    "institutionCCID" : null,
                    "version" : 1,
                    "dateType" : null,
                    "jobTitle" : null,
                    "title" : null
                }
            }
        } 
        
        
        
 

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }